name: nsa_codenames
version: 1.0.0
dependencies:
    angular: any
    bootjack: any
    browser: any
    web_components: any
dependency_overrides:
    route_hierarchical:
        path: /opt/route.dart
transformers:
- angular
